### ISSUE TITLE
Merging Visual Material Repo into Collections Information Repo

### ISSUE THREAD

**Issue by StephCornwell** [wellcomecollection/collections-information#9]
AS A TEST, have been able to successfully merge repositories using forked clones of collections-information and visual material repositories in gitbash and then syncing to personal gitbook (https://github.com/StephCornwell/collections-information = https://s-cornwell.gitbook.io/vmtest/) 

Some edits to VM files needed:
Files
May need to rename some files to reduce confusion like README.md file

Summary Document
The summary document will need to be edited to reflect the changed pathways in github to show properly on gitbook (I've only bothered to change them for the first section in the test). 

In Gitbook, the greyed out headings can only be applied at the top level so will probably be worth creating a planning document of how we would like documentation to be structured on gitbook at a high level before editing the summary as need to create new files to replace those headings in VM repo. Might also be worth thinking about for github to make editing documentation as simple as possible too.

**Comment by StephCornwell** [comment]
@hardytoni Also can't add any labels or assignees to the above as don't have the permissions. If you go into the settings and manage access, you should be able to add or modify individuals existing access (screenshot below):

![EXAMPLE](https://user-images.githubusercontent.com/51817599/137361336-ad550e1f-cfbe-4c29-b27b-373d868665c9.jpg)

I would think Triage would be enough if you want people to be able to manage issues, projects, Write if also want people to be able to submit files to be added to the repository. Admin and Maintain levels seem to be mainly for managing higher level repo settings and access permissions

**Comment by StephCornwell** [comment]
> Summary Document The summary document will need to be edited to reflect the changed pathways in github to show properly on gitbook (I've only bothered to change them for the first section in the test).

UPDATE: Completely forgot that I could just find and replace in the XML file! Now updated in TEST.

**Comment by hardytoni** [comment]
@StephCornwell  I've just realised that I don't seem to have the right settings to be able to allow people to manage issues etc. Will get it sorted!
